---
- hosts: nanokvm
  gather_facts: no

  vars:
    disable_tailscaled: true
    dns: 9.9.9.9
    # uncomment and set to your public key url
    #ssh_keys: https://github.com/markuman.keys

  tasks:
    - name: disable tailscald
      when: disable_tailscaled
      block:
        - name: stop tailscaled
          ansible.builtin.raw: "bash -l -c '/etc/init.d/S98tailscaled stop'"

        - name: disable tailscaled
          ansible.builtin.raw: "bash -l -c 'chmod -x /etc/init.d/S98tailscaled'"



    - name: use dns from dhcp
      when: dns is defined
      block:
        - name: set nameserver
          ansible.builtin.raw: "bash -l -c 'echo \"nameserver {{ dns }}\" > /etc/resolv.conf'"

        - name: make it immutable
          ansible.builtin.raw: "bash -l -c 'chattr +i /etc/resolv.conf'"

    - name: get ssh public keys
      when: ssh_keys is defined and ssh_keys | string is match("^https.*")
      with_items:
        - curl {{ ssh_keys }} >> /root/.ssh/authorized_keys
        - "sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config"
      ansible.builtin.raw: "{{ item }}"

