---
- hosts: nanokvm
  gather_facts: no

  vars:
    disable_tailscaled: true
    disable_router: true
    dns: 9.9.9.9
    # uncomment and set to your public key url
    #ssh_keys: https://github.com/markuman.keys

  pre_tasks:
    - name: check for tailscaled
      ignore_errors: true
      raw:
        test -f /etc/init.d/S98tailscaled
      register: tailscaled_available

    - name: check for tailscale conf
      ignore_errors: true
      raw:
        test -f /etc/sysctl.d/99-tailscale.conf
      register: tailscale_conf_available

  tasks:
    - name: disable tailscald
      when: disable_tailscaled and not tailscaled_available.failed
      block:
        - name: stop tailscaled
          ansible.builtin.raw: "bash -l -c '/etc/init.d/S98tailscaled stop'"

        - name: disable tailscaled
          ansible.builtin.raw: "bash -l -c 'chmod -x /etc/init.d/S98tailscaled'"

    - name: change nameserver - https://github.com/sipeed/NanoKVM/issues/245
      when: dns is defined
      block:
        - name: set nameserver
          ansible.builtin.raw: "bash -l -c 'echo \"nameserver {{ dns }}\" > /etc/resolv.conf'"

        - name: make it immutable
          ansible.builtin.raw: "bash -l -c 'chattr +i /etc/resolv.conf'"

    - name: get ssh public keys and disable password auth
      when: ssh_keys is defined and ssh_keys | string is match("^https.*")
      with_items:
        - curl {{ ssh_keys }} >> /root/.ssh/authorized_keys
        - "sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config"
      ansible.builtin.raw: "{{ item }}"

    - name: disable router - https://github.com/sipeed/NanoKVM/issues/197
      when: disable_router and not tailscale_conf_available.failed
      block:
        - name: empty /etc/sysctl.d/99-tailscale.conf
          ansible.builtin.raw: echo "" > /etc/sysctl.d/99-tailscale.conf

        - name: immutable /etc/sysctl.d/99-tailscale.conf
          ansible.builtin.raw: "bash -l -c 'chattr +i /etc/sysctl.d/99-tailscale.conf'"

